[package]
name = "rest-service"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace dependencies
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }

# Local dependencies
shared = { path = "../shared" }